application:
  title: IMusic
  admin_title: Admin IMusic
  admin: admin
user:
  name:
    max_length: 50
  featured_list: 8
  password:
    minimum: 6
  avatar:
    file_type: ["image/png", "image/jpg", "image/jpeg"]
    max_size: 1
comment:
  list: 30
  datetime_format: "%H:%M %d/%m/%y"
track:
  list: 8
  small_list: 4
  featured_list: 3
  title:
    max_length: 30
  year:
    minimum: 0
    start: 1800
  cover:
    file_type: ["image/png", "image/jpg", "image/jpeg"]
    max_size: 1
  data:
    file_type: "audio/mpeg"
    max_size: 30
  rateable: quality
album:
  list: 16
  featured_list: 8
  name:
    max_length: 70
  year:
    minimum: 0
    start: 1800
  cover:
    file_type: ["image/png", "image/jpg", "image/jpeg"]
    max_size: 1
  rateable: quality
category:
  list: 16
  featured_list: 8
  name:
    max_length: 30
  cover:
    file_type: ["image/png", "image/jpg", "image/jpeg"]
    max_size: 1
artist:
  list: 16
  featured_list: 4
  start_year: 1800
  description:
    limit: 200
  name:
    max_length: 50
  country:
    max_length: 50
  avatar:
    file_type: ["image/png", "image/jpg", "image/jpeg"]
    max_size: 1
lyric:
  featured_list: 4
min_friendly_token: 0
max_friendly_token: 20
omniauth:
  facebook: facebook
  google_oauth2: google_oauth2
